version: '3.8'

volumes:
  pg_data_production:
  static_volume:

services:
  backend:
    image: alexandermolodtsov/kittygram_backend
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"

  db:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    image: alexandermolodtsov/kittygram_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
    restart: unless-stopped
    command: >
      sh -c "cp -r /app/build/. /frontend_static/ && tail -f /dev/null"

  gateway:
    image: alexandermolodtsov/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    command: "nginx -g 'daemon off;'"