services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - static:/app/static
    depends_on:
      - db
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend.wsgi"

  frontend:
    build: ./frontend
    volumes:
      - static:/app/static

  gateway:
    build: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - static:/static
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static: