version: '3.8'

services:
  backend:
    image: alexandermolodtsov/kittygram_backend
    restart: always
    env_file:
      - ./infra/.env
    ports:
      - "8000:8000"

  frontend:
    image: alexandermolodtsov/kittygram_frontend
    restart: always
    ports:
      - "80:80"

  gateway:
    image: alexandermolodtsov/kittygram_gateway
    restart: always
    ports:
      - "1337:1337"
