version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: alexandermolodtsov/kittygram_backend
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: alexandermolodtsov/kittygram_frontend
    volumes:
      - static:/app/static
    depends_on:
      - backend

  gateway:
    image: alexandermolodtsov/kittygram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - "9000:9000"
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
