version: '3.8'

volumes:
  pg_data_production:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    platform: linux/amd64
    image: alexandermolodtsov/kittygram_backend
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static:/backend_static
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    platform: linux/amd64
    image: alexandermolodtsov/kittygram_frontend
    env_file: .env
    restart: always
    volumes:
      - static:/frontend_static
    networks:
      - backend_network

  gateway:
    platform: linux/amd64
    image: alexandermolodtsov/kittygram_gateway
    env_file: .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
