version: '3.8'

volumes:
  pg_data_production:
  static_volume:

services:
  backend:
    image: alexandermolodtsov/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - kittygram_net

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kittygram_net

  frontend:
    image: alexandermolodtsov/kittygram_frontend
    env_file: .env
    command: >
      sh -c "while true; do sleep 86400; done"  # Замена команды на бесконечное ожидание
    volumes:
      - static_volume:/frontend_static
    networks:
      - kittygram_net

  gateway:
    image: alexandermolodtsov/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - kittygram_net

networks:
  kittygram_net:
    driver: bridge