# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:

services:
  backend:
    image: alexandermolodtsov/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: unless-stopped
  frontend:
    image: alexandermolodtsov/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: alexandermolodtsov/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80