version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend/
    image: alexandermolodtsov/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"

  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - static:/static
    command: sh -c "npm run build && cp -r /app/build/. /static/"

  gateway:
    build: ./nginx/
    ports:
      - "9000:9000"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
